services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: MsSqlServer
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=${SA_PASSWORD}
    volumes:
     - ./sqlserver_data:/var/opt/mssql/data
    ports:
     - 1433:1433