services:  

  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Buixuantoan@916263
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432